"""Per-feed adapters: raw file -> normalized row dicts.

Each adapter hides that feed's specific schema/dialect (column names,
delimiter, decimal separator, availability vocabulary, XML vs CSV) and
yields dicts with a shared shape, so `importer.import_row` never needs to
know which shop a row came from.
"""
import csv
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterator

from app.importers.common import derive_model_name, parse_price_cents
from app.taxonomy import gender_for_category


def parse_awin_csv(path: Path) -> Iterator[dict]:
    availability_in_stock = {"in stock", "preorder"}
    with path.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            yield {
                "shop_sku": row["sku"],
                "ean": row["ean"] or None,
                "brand": row["brand"],
                "model_name": derive_model_name(row["product_name"], row["brand"]),
                "description": row["description"],
                "category": row["category"],
                "gender": gender_for_category(row["category"]),
                "size_raw": row["size"],
                "color": row["color"],
                "price_cents": parse_price_cents(row["price"]),
                "list_price_cents": parse_price_cents(row["list_price"]),
                "in_stock": row["availability"] in availability_in_stock,
                "image_url": row["image_url"],
                "deeplink_url": row["deeplink_url"],
            }


_AWIN_LIVE_CATEGORY_MAP = {
    "Herren > Hosen > Jeans": "Herrenjeans",
}


def _awin_live_category(category_path: str) -> str | None:
    """Map an Awin datafeed's merchant category path to a sizehive category.

    Awin's real per-advertiser datafeeds carry the shop's own category tree
    in `merchant_product_category_path` (e.g. "Herren > Hosen > Jeans"), not
    the sample fixtures' flat `category` column. Only paths that resolve to
    one of the three in-scope categories are imported; a "Damen > Hosen >
    Jeans" row has no home here (Herrenjeans is men's-only per the taxonomy)
    and is skipped rather than mis-tagged.
    """
    if category_path in _AWIN_LIVE_CATEGORY_MAP:
        return _AWIN_LIVE_CATEGORY_MAP[category_path]
    if "T-Shirts" in category_path:
        return "T-Shirts"
    if "Sneaker" in category_path:
        return "Sneaker"
    return None


def parse_awin_live_csv(path: Path) -> Iterator[dict]:
    """Parse a real Awin "Create-a-Feed" export (see app.importers.fetch).

    Distinct from parse_awin_csv, which reads the checked-in sample fixture
    generated by scripts/generate_sample_feeds.py — Awin's own field names
    (merchant_product_id, brand_name, search_price, Fashion:size, ...) don't
    match that fixture's simplified schema.
    """
    with path.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            category = _awin_live_category(row["merchant_product_category_path"])
            if category is None:
                continue
            yield {
                "shop_sku": row["merchant_product_id"],
                "ean": row["product_GTIN"] or None,
                "brand": row["brand_name"],
                "model_name": derive_model_name(row["product_name"], row["brand_name"]),
                "description": row["description"],
                "category": category,
                "gender": gender_for_category(category),
                "size_raw": row["Fashion:size"],
                "color": row["colour"],
                "price_cents": parse_price_cents(row["search_price"]),
                "list_price_cents": parse_price_cents(row["rrp_price"]),
                "in_stock": row["in_stock"] == "1",
                "image_url": row["aw_image_url"],
                "deeplink_url": row["aw_deep_link"],
            }


def parse_belboon_csv(path: Path) -> Iterator[dict]:
    availability_in_stock = {"verfuegbar", "auf Lager"}
    with path.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f, delimiter=";"):
            yield {
                "shop_sku": row["ARTIKELNR"],
                "ean": row["EAN_CODE"] or None,
                "brand": row["MARKE"],
                "model_name": derive_model_name(row["TITEL"], row["MARKE"]),
                "description": row["BESCHREIBUNG"],
                "category": row["WARENGRUPPE"],
                "gender": gender_for_category(row["WARENGRUPPE"]),
                "size_raw": row["GROESSE"],
                "color": row["FARBE"],
                "price_cents": parse_price_cents(row["PREIS_EUR"], decimal_sep=","),
                "list_price_cents": parse_price_cents(row["STREICHPREIS_EUR"], decimal_sep=","),
                "in_stock": row["LAGERSTATUS"] in availability_in_stock,
                "image_url": row["BILD"],
                "deeplink_url": row["LINK"],
            }


def parse_tradedoubler_xml(path: Path) -> Iterator[dict]:
    root = ET.parse(path).getroot()
    for p in root.findall("product"):
        text = lambda tag: (p.findtext(tag) or "").strip()
        yield {
            "shop_sku": text("sku"),
            "ean": text("ean") or None,
            "brand": text("brand"),
            "model_name": derive_model_name(text("title"), text("brand")),
            "description": text("description"),
            "category": text("category"),
            "gender": gender_for_category(text("category")),
            "size_raw": text("size"),
            "color": text("colour"),
            "price_cents": parse_price_cents(text("price")),
            "list_price_cents": parse_price_cents(text("rrp")),
            "in_stock": text("in_stock") == "1",
            "image_url": text("image"),
            "deeplink_url": text("url"),
        }
