"""Download real affiliate feeds to local files for the existing parsers to read.

Sample feeds under data/samples/ are checked-in fixtures generated by
scripts/generate_sample_feeds.py. Real feeds fetched here are written to
data/live/ instead, so neither directory ever clobbers the other.

Usage: python -m app.importers.fetch
"""
from pathlib import Path

import httpx

from app.core.config import settings

LIVE_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "live"


def fetch_awin_feed(dest: Path | None = None) -> Path:
    """Stream the Awin product feed configured via AWIN_FEED_URL to `dest`.

    Awin's datafeed URLs already embed the publisher's auth token as a query
    parameter, so no separate credential handling is needed here.
    """
    if not settings.awin_feed_url:
        raise RuntimeError(
            "awin_feed_url is not configured — set AWIN_FEED_URL in backend/.env "
            "to your Awin datafeed download URL"
        )
    dest = dest or LIVE_DIR / "awin.csv"
    dest.parent.mkdir(parents=True, exist_ok=True)

    with httpx.stream("GET", settings.awin_feed_url, follow_redirects=True, timeout=60.0) as response:
        response.raise_for_status()
        with dest.open("wb") as f:
            for chunk in response.iter_bytes():
                f.write(chunk)

    return dest


if __name__ == "__main__":
    path = fetch_awin_feed()
    print(f"[awin] feed written to {path} ({path.stat().st_size} bytes)")
