"""add variant.image_url and variant.created_at

Revision ID: 561931cf0ed4
Revises: e42197cdd111
Create Date: 2026-08-14 11:45:30.524468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561931cf0ed4'
down_revision: Union[str, Sequence[str], None] = 'e42197cdd111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('image_url', sa.String(length=1000), nullable=False))
    op.add_column('variant', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_variant_created_at'), 'variant', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_created_at'), table_name='variant')
    op.drop_column('variant', 'created_at')
    op.drop_column('variant', 'image_url')
    # ### end Alembic commands ###
