"""create shop, product, variant, price_snapshot tables

Revision ID: 92b4f574860e
Revises: 
Create Date: 2026-08-14 11:32:32.127762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b4f574860e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attribute_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_attributes_gin', 'product', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_product_brand'), 'product', ['brand'], unique=False)
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('affiliate_network', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_slug'), 'shop', ['slug'], unique=True)
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shop_sku', sa.String(length=120), nullable=False),
    sa.Column('ean', sa.String(length=20), nullable=True),
    sa.Column('size_raw', sa.String(length=60), nullable=False),
    sa.Column('size_w', sa.Integer(), nullable=True),
    sa.Column('size_l', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'shop_sku', name='uq_variant_shop_sku')
    )
    op.create_index(op.f('ix_variant_product_id'), 'variant', ['product_id'], unique=False)
    op.create_index(op.f('ix_variant_shop_id'), 'variant', ['shop_id'], unique=False)
    op.create_table('price_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('list_price_cents', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshot_captured_at'), 'price_snapshot', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_snapshot_variant_id'), 'price_snapshot', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_snapshot_variant_id'), table_name='price_snapshot')
    op.drop_index(op.f('ix_price_snapshot_captured_at'), table_name='price_snapshot')
    op.drop_table('price_snapshot')
    op.drop_index(op.f('ix_variant_shop_id'), table_name='variant')
    op.drop_index(op.f('ix_variant_product_id'), table_name='variant')
    op.drop_table('variant')
    op.drop_index(op.f('ix_shop_slug'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_index(op.f('ix_product_brand'), table_name='product')
    op.drop_index('ix_product_attributes_gin', table_name='product', postgresql_using='gin')
    op.drop_table('product')
    # ### end Alembic commands ###
